package fun.Yanderov.features.module;

import fun.Yanderov.features.impl.combat.AimBacktrack;
import fun.Yanderov.features.impl.combat.AntiBot;
import fun.Yanderov.features.impl.combat.Aura;
import fun.Yanderov.features.impl.combat.AutoArmor;
import fun.Yanderov.features.impl.combat.AutoCrystal;
import fun.Yanderov.features.impl.combat.AutoECTrap;
import fun.Yanderov.features.impl.combat.AutoGapple;
import fun.Yanderov.features.impl.combat.AutoPotion;
import fun.Yanderov.features.impl.combat.AutoSwap;
import fun.Yanderov.features.impl.combat.AutoTotem;
import fun.Yanderov.features.impl.combat.AutoWeb;
import fun.Yanderov.features.impl.combat.BreachSwap;
import fun.Yanderov.features.impl.combat.Criticals;
import fun.Yanderov.features.impl.combat.CrystalTap;
import fun.Yanderov.features.impl.combat.HitBoxModule;
import fun.Yanderov.features.impl.combat.LagTrack;
import fun.Yanderov.features.impl.combat.MaceAura;
import fun.Yanderov.features.impl.combat.NoFriendDamage;
import fun.Yanderov.features.impl.combat.NoInteract;
import fun.Yanderov.features.impl.combat.ProjectileHelper;
import fun.Yanderov.features.impl.combat.PulseBlink;
import fun.Yanderov.features.impl.combat.Resolver;
import fun.Yanderov.features.impl.combat.ShieldUtility;
import fun.Yanderov.features.impl.combat.ShiftTap;
import fun.Yanderov.features.impl.combat.SuperBow;
import fun.Yanderov.features.impl.combat.SuperKnockback;
import fun.Yanderov.features.impl.combat.TNTbabax;
import fun.Yanderov.features.impl.combat.TPInfluence;
import fun.Yanderov.features.impl.combat.TargetPearl;
import fun.Yanderov.features.impl.combat.TimeManipulation;
import fun.Yanderov.features.impl.combat.TriggerBot;
import fun.Yanderov.features.impl.combat.Velocity;
import fun.Yanderov.features.impl.exploit.ClickTp;
import fun.Yanderov.features.impl.misc.ArrowsSwap;
import fun.Yanderov.features.impl.misc.AutoBuy;
import fun.Yanderov.features.impl.misc.AutoDisable;
import fun.Yanderov.features.impl.misc.AutoDuel;
import fun.Yanderov.features.impl.misc.AutoLeave;
import fun.Yanderov.features.impl.misc.AutoTpAccept;
import fun.Yanderov.features.impl.misc.BlockTrap;
import fun.Yanderov.features.impl.misc.ChatManager;
import fun.Yanderov.features.impl.misc.ChestStealer;
import fun.Yanderov.features.impl.misc.ClickFriend;
import fun.Yanderov.features.impl.misc.ClickPearl;
import fun.Yanderov.features.impl.misc.DeathCoords;
import fun.Yanderov.features.impl.misc.Disabler;
import fun.Yanderov.features.impl.misc.ElytraHelper;
import fun.Yanderov.features.impl.misc.Extinguish;
import fun.Yanderov.features.impl.misc.FastPlace;
import fun.Yanderov.features.impl.misc.FastShulkerBreak;
import fun.Yanderov.features.impl.misc.FlagCheck;
import fun.Yanderov.features.impl.misc.FreeCam;
import fun.Yanderov.features.impl.misc.GhostHand;
import fun.Yanderov.features.impl.misc.GodMode;
import fun.Yanderov.features.impl.misc.HoleFiller;
import fun.Yanderov.features.impl.misc.Hurt;
import fun.Yanderov.features.impl.misc.JoinerHelper;
import fun.Yanderov.features.impl.misc.Magnitism;
import fun.Yanderov.features.impl.misc.MultiActions;
import fun.Yanderov.features.impl.misc.NoSlowBreak;
import fun.Yanderov.features.impl.misc.PacketHandler;
import fun.Yanderov.features.impl.misc.PearleCatching;
import fun.Yanderov.features.impl.misc.Regen;
import fun.Yanderov.features.impl.misc.SelfDestruct;
import fun.Yanderov.features.impl.misc.ServerHelper;
import fun.Yanderov.features.impl.misc.ServerRPSpoofer;
import fun.Yanderov.features.impl.misc.TPLoot;
import fun.Yanderov.features.impl.misc.TabParser;
import fun.Yanderov.features.impl.misc.WindJump;
import fun.Yanderov.features.impl.movement.AirStuck;
import fun.Yanderov.features.impl.movement.AutoSprint;
import fun.Yanderov.features.impl.movement.Blink;
import fun.Yanderov.features.impl.movement.BoatFly;
import fun.Yanderov.features.impl.movement.Clip;
import fun.Yanderov.features.impl.movement.ElytraMotion;
import fun.Yanderov.features.impl.movement.ElytraPlus;
import fun.Yanderov.features.impl.movement.ElytraStrafe;
import fun.Yanderov.features.impl.movement.ElytraTarget;
import fun.Yanderov.features.impl.movement.FakeLag;
import fun.Yanderov.features.impl.movement.Fly;
import fun.Yanderov.features.impl.movement.HeadHiter;
import fun.Yanderov.features.impl.movement.InventoryMove;
import fun.Yanderov.features.impl.movement.Jesus;
import fun.Yanderov.features.impl.movement.KeepSprint;
import fun.Yanderov.features.impl.movement.LongJump;
import fun.Yanderov.features.impl.movement.NoClip;
import fun.Yanderov.features.impl.movement.NoFallDamage;
import fun.Yanderov.features.impl.movement.NoSlow;
import fun.Yanderov.features.impl.movement.NoWeb;
import fun.Yanderov.features.impl.movement.Speed;
import fun.Yanderov.features.impl.movement.Spider;
import fun.Yanderov.features.impl.movement.Step;
import fun.Yanderov.features.impl.movement.Stopper;
import fun.Yanderov.features.impl.movement.Strafe;
import fun.Yanderov.features.impl.movement.SuperFireWork;
import fun.Yanderov.features.impl.movement.TargetStrafe;
import fun.Yanderov.features.impl.movement.TickRangeManipulator;
import fun.Yanderov.features.impl.movement.WaterSpeed;
import fun.Yanderov.features.impl.player.AhHelper;
import fun.Yanderov.features.impl.player.AntiAFK;
import fun.Yanderov.features.impl.player.AutoBreak;
import fun.Yanderov.features.impl.player.AutoCreeperFarm;
import fun.Yanderov.features.impl.player.AutoDodge;
import fun.Yanderov.features.impl.player.AutoFish;
import fun.Yanderov.features.impl.player.AutoPilot;
import fun.Yanderov.features.impl.player.AutoRespawn;
import fun.Yanderov.features.impl.player.AutoTool;
import fun.Yanderov.features.impl.player.AutoUse;
import fun.Yanderov.features.impl.player.AutoWalk;
import fun.Yanderov.features.impl.player.FastBreak;
import fun.Yanderov.features.impl.player.FastUse;
import fun.Yanderov.features.impl.player.FreeLook;
import fun.Yanderov.features.impl.player.ItemScroller;
import fun.Yanderov.features.impl.player.NameProtect;
import fun.Yanderov.features.impl.player.NoDelay;
import fun.Yanderov.features.impl.player.NoEntityTrace;
import fun.Yanderov.features.impl.player.NoPush;
import fun.Yanderov.features.impl.player.NoRotateSet;
import fun.Yanderov.features.impl.player.NoSlotSet;
import fun.Yanderov.features.impl.render.Arrows;
import fun.Yanderov.features.impl.render.AspectRatio;
import fun.Yanderov.features.impl.render.BetterMinecraft;
import fun.Yanderov.features.impl.render.BlockESP;
import fun.Yanderov.features.impl.render.BlockOverlay;
import fun.Yanderov.features.impl.render.CameraSettings;
import fun.Yanderov.features.impl.render.CrossHair;
import fun.Yanderov.features.impl.render.Esp;
import fun.Yanderov.features.impl.render.FriendCrystal;
import fun.Yanderov.features.impl.render.HitEffect;
import fun.Yanderov.features.impl.render.Hud;
import fun.Yanderov.features.impl.render.JumpCircle;
import fun.Yanderov.features.impl.render.KillEffect;
import fun.Yanderov.features.impl.render.NoRender;
import fun.Yanderov.features.impl.render.ProjectilePrediction;
import fun.Yanderov.features.impl.render.SeeInvisible;
import fun.Yanderov.features.impl.render.SwingAnimation;
import fun.Yanderov.features.impl.render.TargetESP;
import fun.Yanderov.features.impl.render.ViewModel;
import fun.Yanderov.features.impl.render.WorldParticles;
import fun.Yanderov.features.impl.render.WorldTweaks;
import fun.Yanderov.features.impl.render.XRay;
import java.util.ArrayList;
import java.util.List;

public class ModuleRepository {
   private final List modules = new ArrayList();

   public void setup() {
      this.register(new AntiAFK(), new JumpCircle(), new BreachSwap(), new BetterMinecraft(), new ProjectileHelper(), new TargetStrafe(), new Strafe(), new AutoPilot(), new AirStuck(), new MaceAura(), new PearleCatching(), new LagTrack(), new NoEntityTrace(), new NoFallDamage(), new ElytraMotion(), new ElytraStrafe(), new AutoPotion(), new AutoWeb(), new LongJump(), new ShiftTap(), new AspectRatio(), new FreeLook(), new ClickPearl(), new ClickFriend(), new TabParser(), new WindJump(), new TargetESP(), new NoWeb(), new ServerHelper(), new WaterSpeed(), new ItemScroller(), new Hud(), new AhHelper(), new ProjectilePrediction(), new WorldParticles(), new ChatManager(), new ElytraTarget(), new PulseBlink(), new XRay(), new TriggerBot(), new Criticals(), new Aura(), new Resolver(), new Stopper(), new ShieldUtility(), new TPInfluence(), new AimBacktrack(), new AutoECTrap(), new AutoGapple(), new CrystalTap(), new TNTbabax(), new TimeManipulation(), new SuperKnockback(), new AutoSwap(), new SuperBow(), new NoFriendDamage(), new HitBoxModule(), new AntiBot(), new BoatFly(), new AutoCrystal(), new AutoSprint(), new NoPush(), new ElytraHelper(), new JoinerHelper(), new ArrowsSwap(), new Disabler(), new FastShulkerBreak(), new GodMode(), new Magnitism(), new PacketHandler(), new Regen(), new GhostHand(), new MultiActions(), new BlockTrap(), new Extinguish(), new FastPlace(), new NoSlowBreak(), new HoleFiller(), new Hurt(), new FreeCam(), new AutoDuel(), new DeathCoords(), new TPLoot(), new AutoDisable(), new FlagCheck(), new NoDelay(), new Velocity(), new AutoRespawn(), new NoSlow(), new InventoryMove(), new Blink(), new AutoTool(), new Fly(), new HeadHiter(), new KeepSprint(), new ElytraPlus(), new FakeLag(), new TickRangeManipulator(), new FastBreak(), new CameraSettings(), new Speed(), new Step(), new SwingAnimation(), new ViewModel(), new BlockOverlay(), new Jesus(), new Esp(), new BlockESP(), new AutoTotem(), new AutoCreeperFarm(), new AutoDodge(), new AutoBreak(), new AutoFish(), new FastUse(), new AutoWalk(), new NoRotateSet(), new NoSlotSet(), new ChestStealer(), new AutoTpAccept(), new Arrows(), new AutoLeave(), new HitEffect(), new WorldTweaks(), new NoClip(), new Clip(), new ClickTp(), new NoRender(), new AutoBuy(), new NameProtect(), new SelfDestruct(), new SeeInvisible(), new TargetPearl(), new AutoArmor(), new AutoUse(), new NoInteract(), new CrossHair(), new SuperFireWork(), new Spider(), new FriendCrystal(), new ServerRPSpoofer(), new KillEffect());
      this.modules.sort((m1, m2) -> ((Module)m1).getName().compareToIgnoreCase(((Module)m2).getName()));
   }

   public void register(Module... module) {
      this.modules.addAll(List.of(module));
   }

   public List modules() {
      return this.modules;
   }
}

